### ISSUE TITLE
500 Internal Server Error for all pages except the homepage

### ISSUE THREAD

**Issue by hamsn** [eschnou/storytlr#47] opened 2011-07-27 06:30 UTC
After installing sorytlr on my shared hosting, I could open the homepage correctly, but the admin page, or login page or the stories tab on frontpage give 500 Internal Server Error.

I am not sure what is causing this issue.

**Comment by eschnou** [comment] 2013-01-10 20:29
Apologizes for never coming back to you, life has been hectic. I'm now busy catching up on issues and fixing things. A lot has been fixed and merged in the dev branch.

The issue is most likely due to a missing php module. Looking at the Apache error log usually gives you a clue on what is going wrong. I've added additional checks in the install code for missing modules. So if you want to try with the latest code on the dev branch it may help.

**Closed as completed by eschnou** 2013-01-10 20:29 UTC
Labels: issue
