### ISSUE TITLE
Error when adding Flickr stream

### ISSUE THREAD

**Issue by brim415** [eschnou/storytlr#57] opened 2012-03-07 21:38 UTC
I can't add the streams for our Flickr accounts. When I type in our usernames for those sites, I just get an error message. I've already added Twitter and youTube without any problems.

Is there something I'm missing in the back end CMS? Or is there a line of code I need to edit?

**Comment by eschnou** [comment] 2012-03-08 08:06
For flickr, you need to add a developer key in the config.ini file

**Comment by brim415** [comment] 2012-03-12 14:26
I have a flickr api in the config.ini, still won't add either flickr or vimeo. Here's the error text specifically:

There was an error while importing the data. Please doublecheck your import configuration and try again later. Let us know if this problem persists.

Currently I have them both set up as RSS feeds, but it'd be ideal to use the sources specifically so they can contribute to the photos and videos pages.

**Comment by eschnou** [comment] 2012-03-14 21:14
- There should be some logs in protected/logs/ - if you see anything unusual, could you please post it here ?
- You can also activate the debug mode (set debug to 1 in config.ini)

**Comment by brim415** [comment] 2012-03-15 14:28
Went into debug mode, and tried to add flickr account again. Here is the log message:

2012-03-07T17:43:48+01:00 ERR (3): Exception updating flickr (3): Flickr return fail when asking for user bcworkshop at url http://api.flickr.com/services/rest/?method=flickr.urls.lookupUser&api_key=&url=http%3A%2F%2Fwww.flickr.com%2Fphotos%2Fbcworkshop&format=json&nojsoncallback=1 

I have the api key entered in config.ini also...

**Comment by eschnou** [comment] 2012-03-15 16:52
In the url showned in this error, the api_key is empty. Are you sure your entry in the config file is correct ?
;; Flickr settings
flickr.api_key=<yourkey>
^^ did you properly uncomment the line ?

**Comment by brim415** [comment] 2012-03-15 17:02
Aaaaaah...that did it. Sorry, I'm not a coder by trade, so I didn't know about uncommenting. Pardon my newness :)

Any thoughts on the Vimeo part, though?

**Comment by eschnou** [comment] 2012-03-15 17:04
No worries, the fault is on the lack of documentation :-) 

For Vimeo, can you file a separate issue (so i can close this one wrt flickr) and also provide any kind of error log associated with adding vimeo ? Or more details on what the problem is (an error or everything fine but 0 items ?). Having your vimeo username will also help.

**Closed as completed by eschnou** 2012-03-15 17:04 UTC
Labels: user support
