### ISSUE TITLE
CSS Issue?

### ISSUE THREAD

**Issue by mlcjohnson16** [eschnou/storytlr#32] opened 2010-11-21 04:58 UTC
I just got my lifestream up and running at www.joshandjen.net, but I'm having some trouble with the layout.  I'm using the packaged themes, but if you take a look at the site you'll notice that the links section doesn't seem to be displaying correctly.  It looks fine in Firefox, but Chrome and IE are struggling.  Any ideas what I can do to fix this?  I'm a hack at CSS style sheets.  

http://www.joshandjen.net

**Comment by alardw** [comment] 2010-11-22 08:11
The issue is caused by the long url and the browser does not know how to properly display it, in such a small space. Long urls also look a bit ugly ;) 

The best fix is to edit the link titles and give them a descriptive title (with spaces) and you're good to go. Other solutions (e.g. inserting spaces in the url with javascript so it wraps) tend to be overkill and dirty.

Hope this helps!

Alard

**Comment by eschnou** [comment] 2011-01-14 20:31
Not an issue then, I'm closing it.

**Closed as completed by eschnou** 2011-01-14 20:31 UTC
